THESE:
Wie unterscheiden sich die Gesamt-Sterberaten zwischen Ländern im Jahr X

In [2]:
import pandas as pd

In [7]:
df = pd.read_csv("Data_Files/base_data104_with_lookup.csv", low_memory=False)

Zuerst suchen wir das Jahr X bei dem es am meisten verschiedene Länder gibt. Dieses eignet sich am besten für die weiterführende Analyse.

In [8]:
# Anzahl Länder pro Jahr
df_year_counts = df.groupby("Year")["Country"].nunique().reset_index()

df_year_counts.columns = ["Year", "NumCountries"]
df_year_counts.sort_values("NumCountries", ascending=False)

    Year  NumCountries
21  2009            97
22  2010            95
29  2017            93
24  2012            93
28  2016            93
25  2013            93
26  2014            93
30  2018            92
27  2015            91
23  2011            91
20  2008            90
19  2007            87
18  2006            86
31  2019            85
14  2002            83
15  2003            83
17  2005            82
16  2004            82
13  2001            81
33  2021            75
32  2020            74
12  2000            70
11  1999            57
34  2022            51
10  1998            42
9   1997            34
8   1996            22
35  2023            18
7   1995            11
6   1994             3
1   1989             1
0   1988             1
3   1991             1
2   1990             1
4   1992             1
5   1993             1

Wir werden mit dem Jahr 2009 fortfahren. Zuerst summieren wir die Todesfälle pro Land im Jahr 2009

In [10]:
df_2009 = df[df["Year"] == 2009]
death_col = "Deaths at all ages"  

df_deaths = (
    df_2009.groupby("Country", as_index=False)[death_col]
           .sum()
)
df_deaths.head()

               Country  Deaths at all ages
0             Anguilla                 140
1  Antigua and Barbuda                 744
2            Argentina              603736
3                Aruba                1224
4            Australia              281520

Wir haben ein Csv File erstellt, dass die Populationsdaten aller Länder, die wir brauchen, enthält. Quelle: